# Generated by Django 3.0.4 on 2020-03-19 22:27

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', wagtail.core.fields.RichTextField(max_length=255)),
                ('description', wagtail.core.fields.RichTextField(max_length=1000)),
                ('case_url', models.CharField(max_length=200)),
            ],
        ),
    ]
